# Changes here will be overwritten by Copier
_commit: v0.2.0
_src_path: gh:alan-turing-institute/python-project-template
coc: our_coc
email: edable-heath@turing.ac.uk
full_name: Edmund Dable-Heath
license: MIT
min_python_version: '3.10'
org: alan-turing-institute
project_name: ARC-SPICE
project_short_description: Sample Level, Pipeline Introduced Cumulative Errors (SPICE).
    Investigating methods for generalisable measurement of cumulative errors in multi-model
    (and multi-modal) ML pipelines.
python_name: arc_spice
typing: loose
url: https://github.com/alan-turing-institute/ARC-SPICE
