ocr:
  specific_task: "image-to-text"
  model: "microsoft/trocr-base-handwritten"

translator:
  specific_task: "translation_fr_to_en"
  model: "ybanas/autotrain-fr-en-translate-51410121895"

classifier:
  specific_task: "text-classification"
  model: "../distilbert-topic-classifier/"
  kwargs:
    truncation : True
    padding : True
