ocr:
  model: "microsoft/trocr-small-printed"

translator:
  specific_task: "translation_fr_to_en"
  model: "ybanas/autotrain-fr-en-translate-51410121895"

classifier:
  specific_task: "zero-shot-classification"
  model: "claritylab/zero-shot-explicit-binary-bert"
